### ISSUE TITLE
error when building on manjaro

### ISSUE THREAD

**Issue by serauchiha** [andrewrk/groovebasin#474]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@3.3.5
3 info using node@v4.1.2
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle groovebasin@1.5.1~prebuild: groovebasin@1.5.1
6 silly lifecycle groovebasin@1.5.1~prebuild: no script for prebuild, continuing
7 info lifecycle groovebasin@1.5.1~build: groovebasin@1.5.1
8 verbose lifecycle groovebasin@1.5.1~build: unsafe-perm in lifecycle true
9 verbose lifecycle groovebasin@1.5.1~build: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/sera/groovebasin/node_modules/.bin:/usr/l$
10 verbose lifecycle groovebasin@1.5.1~build: CWD: /home/sera/groovebasin
11 silly lifecycle groovebasin@1.5.1~build: Args: [ '-c', 'npm install && ./build' ]
12 silly lifecycle groovebasin@1.5.1~build: Returned: code: 1  signal: null
13 info lifecycle groovebasin@1.5.1~build: Failed to exec build script
14 verbose stack Error: groovebasin@1.5.1 build: `npm install && ./build`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:233:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:818:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid groovebasin@1.5.1
16 verbose cwd /home/sera/groovebasin
17 error Linux 3.16.7.4-1-MANJARO
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
19 error node v4.1.2
20 error npm  v3.3.5
21 error code ELIFECYCLE
22 error groovebasin@1.5.1 build: `npm install && ./build`
22 error Exit status 1
23 error Failed at the groovebasin@1.5.1 build script 'npm install && ./build'.
23 error This is most likely a problem with the groovebasin package,
24 verbose exit [ 1, true ]

**Comment by andrewrk** [comment]
Unfortunately, nothing that npm outputs is actually an error log. Can you post the actual stderr output of the build?

**Comment by fa7ad** [comment]
Groovebasin doesn't compile with anything newer than the 0.12.x series of node. The error seems to come from some *C* or *C++* header.

```log

> groove@2.3.4 install /tmp/fahad/yaourt-tmp-fahad/aur-nodejs-groovebasin/src/groovebasin-1.5.1/node_modules/groove
> node-gyp rebuild

make: Entering directory '/tmp/fahad/yaourt-tmp-fahad/aur-nodejs-groovebasin/src/groovebasin-1.5.1/node_modules/groove/build'
  CXX(target) Release/obj.target/groove/src/groove.o
In file included from ../src/groove.cc:2:0:
../../nan/nan.h:261:25: error: redefinition of ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Local<T>)’
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                         ^~~~~~~~~~~~~~~
../../nan/nan.h:256:25: note: ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Handle<T>)’ previously declared here
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                         ^~~~~~~~~~~~~~~
../../nan/nan.h:661:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^~~~~~~
../../nan/nan.h:661:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^~~~~~~~
../../nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../../nan/nan.h:665:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^~~~~~~~
../../nan/nan.h:665:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^~~~
../../nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../../nan/nan.h:672:67: error: no matching function for call to ‘New(v8::Isolate*, const char*&, uint32_t&)’
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
In file included from ../../nan/nan.h:25:0,
                 from ../src/groove.cc:2:
/home/fahad/.node-gyp/4.4.7/include/node/node_buffer.h:31:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^~~
/home/fahad/.node-gyp/4.4.7/include/node/node_buffer.h:31:40: note:   conversion of argument 3 would be ill-formed:
In file included from ../src/groove.cc:2:0:
../../nan/nan.h:672:67: error: invalid conversion from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’ [-fpermissive]
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
In file included from ../../nan/nan.h:25:0,
                 from ../src/groove.cc:2:
/home/fahad/.node-gyp/4.4.7/include/node/node_buffer.h:43:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^~~
/home/fahad/.node-gyp/4.4.7/include/node/node_buffer.h:43:40: note:   conversion of argument 2 would be ill-formed:
In file included from ../src/groove.cc:2:0:
../../nan/nan.h:672:67: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../../nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../../nan/nan.h:676:29: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
            ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../../nan/nan.h:683:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^~~~
make: *** [groove.target.mk:97: Release/obj.target/groove/src/groove.o] Error 1
make: Leaving directory '/tmp/fahad/yaourt-tmp-fahad/aur-nodejs-groovebasin/src/groovebasin-1.5.1/node_modules/groove/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.7.4-1-ARCH
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/fahad/yaourt-tmp-fahad/aur-nodejs-groovebasin/src/groovebasin-1.5.1/node_modules/groove
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
```
